name: Generate Sponsors README
on:
  schedule:
    - cron: 30 15 * * 0-6
    
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2
      - name: Generate Sponsors 💖
        uses: JamesIves/github-sponsors-readme-action@1.0.5
        with:
          token: ${{ secrets.PAT }}
          file: 'README.md'
          marker: 'real-sponsors'
          template: '<a href="https://github.com/sponsors/steveruizok"><img src="https://github.com/{{{ login }}}.png" width="32px" alt="" /></a>'
      - name: Deploy to GitHub Pages 🚀
        uses: JamesIves/github-pages-deploy-action@4.1.1
        with:
          branch: main
          folder: '.'
